name: ical
version: 0.3.0
description: >-
  A library to generate/serialize iCalendar files
homepage: https://github.com/dartclub/ical
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  intl: ^0.19.0
  nanoid: ^1.0.0

dev_dependencies:
  test: ^1.19.3
